# Generated by Django 4.2.5 on 2023-11-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultos/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Edades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela_Dominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Las_Escuela_Dominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edades', models.CharField(max_length=10)),
                ('maestro', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='escuela_dominical/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Las_Sociedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sociedades/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Los_Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ministerios/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(max_length=25)),
                ('Numero_Cedula', models.CharField(max_length=13, unique=True)),
                ('Numero_Celular', models.CharField(max_length=12)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Direccion_Residencia', models.CharField(max_length=50)),
                ('Fecha_Conversion', models.DateField()),
                ('Fecha_Bautizo', models.DateField()),
                ('Sociedad', models.CharField(choices=[('Niños', 'Niños'), ('Jóvenes', 'Jóvenes'), ('Caballeros', 'Caballeros'), ('Damas', 'Damas')], max_length=10)),
                ('Imagen', models.ImageField(upload_to='miembros/imagenes')),
                ('Edades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.edades')),
                ('Escuela_Dominical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.escuela_dominical')),
                ('Ministerios', models.ManyToManyField(related_name='miembros', to='miembros.ministerio')),
            ],
        ),
    ]
