# Generated by Django 4.2.5 on 2023-11-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_edades_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edades',
            name='miembros',
        ),
        migrations.AlterField(
            model_name='culto',
            name='imagen',
            field=models.ImageField(default=2, upload_to='cultos/imagenes'),
            preserve_default=False,
        ),
    ]
