# Generated by Django 4.2.5 on 2023-11-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_alter_culto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='Correo_Electronico',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Direccion_Residencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Escuela_Dominical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.escuela_dominical'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='miembros/imagenes'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Numero_Cedula',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Numero_Celular',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
