# Generated by Django 4.2.5 on 2023-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_alter_miembro_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='Imagen',
            field=models.ImageField(upload_to='miembros/imagenes'),
        ),
    ]
