# Generated by Django 4.2.5 on 2023-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_alter_actividad_imagen_alter_culto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='servicios/imagenes/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Actividade',
        ),
        migrations.RenameModel(
            old_name='Las_Escuela_Dominical',
            new_name='Esc_Dom',
        ),
        migrations.RenameModel(
            old_name='Los_Ministerio',
            new_name='Minist',
        ),
        migrations.RenameModel(
            old_name='Las_Sociedade',
            new_name='Socie',
        ),
        migrations.DeleteModel(
            name='Culto',
        ),
    ]
