# Generated by Django 4.2.5 on 2023-11-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_servicio_rename_actividad_actividade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
