# Generated by Django 4.2.5 on 2023-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0009_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esc_dom',
            name='maestro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Sociedad',
            field=models.CharField(choices=[('Niños', 'Niños'), ('Jóvenes', 'Jóvenes'), ('Caballeros', 'Caballeros'), ('Damas', 'Damas')], max_length=25),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='dia',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora',
            field=models.CharField(max_length=15),
        ),
    ]
