# Generated by Django 4.2.5 on 2023-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0010_alter_esc_dom_maestro_alter_miembro_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='dia',
            field=models.CharField(max_length=50),
        ),
    ]
