# Generated by Django 4.2.5 on 2023-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0011_alter_servicio_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='Fecha_Bautizo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Fecha_Conversion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
