# Generated by Django 4.2.5 on 2023-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0012_alter_miembro_fecha_bautizo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividade',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
