# Generated by Django 4.2.5 on 2024-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0013_alter_actividade_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='Estatus_Miembro',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Descarriado', 'Descarriado')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
